import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import profilePic from '../../public/images/profile/developer-pic-1.png'
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link'
import { LinkArrow } from '@/components/icons'
import HireMe from '@/components/HireMe'
import lightBulb from '../../public/images/svgs/miscellaneous_icons_1.svg'
import Transition from '@/components/Transition'


export default function Home() {
  return (
    <>
      <Head>
        <title>Priyanshu Mittal</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Transition></Transition>
      <main className=' flex items-center text-dark w-full min-h-screen dark:text-light'>
        <Layout className=' pt-0 md:pt-16 sm:pt-0'>
          <div className=' flex items-center justify-between w-full lg:flex-col'>
            <div className=' w-1/2 md:w-full'>
              <Image priority src={profilePic} alt='priyanshu' className='w-full h-auto lg:hidden md:inline-block md:w-full' sizes='(max-width:768px) 100vw,(max-width:1200px) 50vw,50vw'></Image>
            </div>
            <div className=' w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center'>
              <AnimatedText text='Turning Vision Into Reality With Code And Design. ' className=' !text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl'></AnimatedText>
              <p className=' my-4 text-base font-medium md:text-sm sm:text-xs'>Aspiring machine learning engineer and full-stack developer with a passion for building intelligent systems and interactive web applications.</p>
              <div className=' flex items-center self-start mt-2 lg:self-center'>
                <Link href='/priyanshu_resume.pdf' target={"_blank"} className=' flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light md:p-2 md:px-4 md:text-base' download={true}>Resume <LinkArrow className={"w-6 ml-1"} /></Link>
                <Link
                href='mailto:priyanshumittal0916@gmail.com' className=' ml-4 text-lg font-medium capitalize text-dark underline dark:text-light md:text-base'>Contact</Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe></HireMe>
        <div className=' absolute right-8 bottom-8 inline-block w-24 md:hidden'>
          <Image src={lightBulb} alt='bulb' className=' w-full h-auto'></Image>
        </div>
      </main>
    </>
  )
}
